spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    #url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/restaurante-db}
    #username: ${SPRING_DATASOURCE_USERNAME:restaurante}
    #password: ${SPRING_DATASOURCE_PASSWORD:senha}
  jpa:
    show-sql: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    spring:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
server:
  port: 8080
  servlet.context-path: /api-restaurante
